version: '3.3'

services:
  mysql-db:
    image: mysql:5.7.28
    container_name: mysql-db
    hostname: mysql-db
    network_mode: host
    labels:
        - "traefik.tcp.routers.mysql.rule=HostSNI(*)"
    ports:
      - "3306:3306"
    environment:
      - TZ=Asia/Kolkata
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_ROOT_HOST=%